server:
  port: 8082

spring:
  application:
    name: pointbank-banking-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banking_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: pointbank
    password: pointbank

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
